### ISSUE TITLE
TypeError: cannot pickle 'pygicp.FastGICP' object

### ISSUE THREAD

**Issue by KwanWaiPang** [Lab-of-AI-and-Robotics/GS_ICP_SLAM#13]
Dear author,
First of all, I would like to thank the open source code for your excellent work!
I completely install requirements & submoules, then tried to run code.
But It doesn't work.

<img width="473" alt="微信图片_20240411140031" src="https://github.com/Lab-of-AI-and-Robotics/GS_ICP_SLAM/assets/44108932/7987724e-2f1a-4366-8ef7-afcf694b5934">

  File "/home/gwp/miniconda3/envs/gsicpslam/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'pygicp.FastGICP' object
[W CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]

**Comment by KwanWaiPang** [comment]
This problem has be solved by install the PCL correctly:
pip install pcl
conda config --add channels conda-forge
conda install -c sirokujira python-pcl

**Comment by 3DV-Coder** [comment]
I have the same problem, and I follow your solution install pcl and python-pcl. 
But this problem still remains.
Do you have some advice to solve this?

pip list  as the follow:
``` 
Package                       Version
----------------------------- -----------
actionlib                     1.12.1
addict                        2.4.0
angles                        1.9.12
attrs                         23.2.0
backcall                      0.2.0
bondpy                        1.8.5
brotlipy                      0.7.0
camera_calibration            1.15.2
camera_calibration_parsers    1.11.13
catkin                        0.7.29
certifi                       2022.12.7
cffi                          1.15.0
charset-normalizer            2.0.4
click                         8.1.7
comm                          0.1.4
ConfigArgParse                1.7
controller_manager            0.18.4
controller_manager_msgs       0.18.4
cryptography                  39.0.1
cv_bridge                     1.13.1
cycler                        0.11.0
Cython                        3.0.10
dash                          2.15.0
dash-core-components          2.0.0
dash-html-components          2.0.0
dash-table                    5.0.0
decorator                     5.1.1
diagnostic_analysis           1.9.7
diagnostic_common_diagnostics 1.9.7
diagnostic_updater            1.9.7
diff-gaussian-rasterization   0.0.0
dynamic_reconfigure           1.6.5
fastjsonschema                2.19.1
filelock                      3.12.2
Flask                         2.2.5
flit_core                     3.6.0
fonttools                     4.38.0
gazebo_plugins                2.8.7
gazebo_ros                    2.8.7
gencpp                        0.6.6
geneus                        2.2.6
genlisp                       0.4.16
genmsg                        0.5.17
gennodejs                     2.0.1
genpy                         0.6.16
idna                          3.4
image_geometry                1.13.1
importlib-metadata            6.7.0
importlib-resources           5.12.0
interactive-markers           1.11.5
ipython                       7.34.0
ipywidgets                    8.1.2
itsdangerous                  2.1.2
jedi                          0.19.1
Jinja2                        3.1.3
joblib                        1.3.2
joint_state_publisher         1.12.15
jsonschema                    4.17.3
jupyter_core                  4.12.0
jupyterlab_widgets            3.0.10
kdl-parser-py                 1.13.3
kiwisolver                    1.4.5
laser_geometry                1.6.7
MarkupSafe                    2.1.5
matplotlib                    3.5.3
matplotlib-inline             0.1.6
message_filters               1.14.13
mkl-fft                       1.3.1
mkl-random                    1.2.2
mkl-service                   2.4.0
nbformat                      5.7.0
nest-asyncio                  1.6.0
nose                          1.3.7
numpy                         1.21.5
open3d                        0.17.0
opencv-contrib-python         4.9.0.80
packaging                     24.0
pandas                        1.1.5
parso                         0.8.4
pcl                           0.0.0.post1
pexpect                       4.9.0
pickleshare                   0.7.5
Pillow                        9.4.0
pip                           22.3.1
pkgutil_resolve_name          1.3.10
plotly                        5.18.0
plyfile                       0.9
prompt-toolkit                3.0.43
ptyprocess                    0.7.0
pycparser                     2.21
pygicp                        0.0.1
Pygments                      2.17.2
pyOpenSSL                     23.0.0
pyparsing                     3.1.2
pyquaternion                  0.9.9
pyrsistent                    0.19.3
PySocks                       1.7.1
python-dateutil               2.9.0.post0
python-pcl                    0.3.0a1
python_qt_binding             0.4.4
pytz                          2024.1
PyYAML                        6.0.1
qt-dotgraph                   0.4.2
qt-gui                        0.4.2
qt-gui-cpp                    0.4.2
qt-gui-py-common              0.4.2
requests                      2.28.1
resource_retriever            1.12.7
retrying                      1.3.4
rosbag                        1.14.13
rosboost-cfg                  1.14.9
rosclean                      1.14.9
roscreate                     1.14.9
rosgraph                      1.14.13
roslaunch                     1.14.13
roslib                        1.14.9
roslint                       0.11.2
roslz4                        1.14.13
rosmake                       1.14.9
rosmaster                     1.14.13
rosmsg                        1.14.13
rosnode                       1.14.13
rosparam                      1.14.13
rospy                         1.14.13
rosservice                    1.14.13
rostest                       1.14.13
rostopic                      1.14.13
rosunit                       1.14.9
roswtf                        1.14.13
rqt_action                    0.4.9
rqt_bag                       0.5.1
rqt_bag_plugins               0.5.1
rqt_console                   0.4.9
rqt_dep                       0.4.9
rqt_graph                     0.4.11
rqt_gui                       0.5.3
rqt_gui_py                    0.5.3
rqt-image-view                0.4.17
rqt_launch                    0.4.8
rqt_logger_level              0.4.8
rqt-moveit                    0.5.10
rqt_msg                       0.4.8
rqt_nav_view                  0.5.7
rqt_plot                      0.4.13
rqt_pose_view                 0.5.8
rqt_publisher                 0.4.8
rqt_py_common                 0.5.3
rqt_py_console                0.4.8
rqt-reconfigure               0.5.4
rqt_robot_dashboard           0.5.7
rqt-robot-monitor             0.5.14
rqt_robot_steering            0.5.10
rqt_runtime_monitor           0.5.7
rqt-rviz                      0.7.0
rqt_service_caller            0.4.8
rqt_shell                     0.4.9
rqt_srv                       0.4.8
rqt_tf_tree                   0.6.0
rqt_top                       0.4.8
rqt_topic                     0.4.11
rqt_web                       0.4.8
rviz                          1.13.30
scikit-learn                  1.0.2
scipy                         1.7.3
sensor-msgs                   1.12.8
setuptools                    65.6.3
simple-knn                    0.0.0
six                           1.16.0
smach                         2.0.3
smach_ros                     2.0.3
smclib                        1.8.5
tenacity                      8.2.3
tf                            1.12.1
tf_conversions                1.12.1
tf2_geometry_msgs             0.6.5
tf2_kdl                       0.6.5
tf2_py                        0.6.5
tf2_ros                       0.6.5
threadpoolctl                 3.1.0
topic_tools                   1.14.13
torch                         1.12.1
torchaudio                    0.12.1
torchmetrics                  0.11.4
torchvision                   0.13.1
tqdm                          4.66.2
traitlets                     5.9.0
typing_extensions             4.4.0
urdfdom-py                    0.4.6
urllib3                       1.26.14
wcwidth                       0.2.13
Werkzeug                      2.2.3
wheel                         0.38.4
widgetsnbextension            4.0.10
xacro                         1.13.20
zipp                          3.15.0

```

**Comment by kk6398** [comment]
> I have the same problem, and I follow your solution install pcl and python-pcl. But this problem still remains. Do you have some advice to solve this?
> 
> pip list as the follow:
> 
> ```
> Package                       Version
> ----------------------------- -----------
> actionlib                     1.12.1
> addict                        2.4.0
> angles                        1.9.12
> attrs                         23.2.0
> backcall                      0.2.0
> bondpy                        1.8.5
> brotlipy                      0.7.0
> camera_calibration            1.15.2
> camera_calibration_parsers    1.11.13
> catkin                        0.7.29
> certifi                       2022.12.7
> cffi                          1.15.0
> charset-normalizer            2.0.4
> click                         8.1.7
> comm                          0.1.4
> ConfigArgParse                1.7
> controller_manager            0.18.4
> controller_manager_msgs       0.18.4
> cryptography                  39.0.1
> cv_bridge                     1.13.1
> cycler                        0.11.0
> Cython                        3.0.10
> dash                          2.15.0
> dash-core-components          2.0.0
> dash-html-components          2.0.0
> dash-table                    5.0.0
> decorator                     5.1.1
> diagnostic_analysis           1.9.7
> diagnostic_common_diagnostics 1.9.7
> diagnostic_updater            1.9.7
> diff-gaussian-rasterization   0.0.0
> dynamic_reconfigure           1.6.5
> fastjsonschema                2.19.1
> filelock                      3.12.2
> Flask                         2.2.5
> flit_core                     3.6.0
> fonttools                     4.38.0
> gazebo_plugins                2.8.7
> gazebo_ros                    2.8.7
> gencpp                        0.6.6
> geneus                        2.2.6
> genlisp                       0.4.16
> genmsg                        0.5.17
> gennodejs                     2.0.1
> genpy                         0.6.16
> idna                          3.4
> image_geometry                1.13.1
> importlib-metadata            6.7.0
> importlib-resources           5.12.0
> interactive-markers           1.11.5
> ipython                       7.34.0
> ipywidgets                    8.1.2
> itsdangerous                  2.1.2
> jedi                          0.19.1
> Jinja2                        3.1.3
> joblib                        1.3.2
> joint_state_publisher         1.12.15
> jsonschema                    4.17.3
> jupyter_core                  4.12.0
> jupyterlab_widgets            3.0.10
> kdl-parser-py                 1.13.3
> kiwisolver                    1.4.5
> laser_geometry                1.6.7
> MarkupSafe                    2.1.5
> matplotlib                    3.5.3
> matplotlib-inline             0.1.6
> message_filters               1.14.13
> mkl-fft                       1.3.1
> mkl-random                    1.2.2
> mkl-service                   2.4.0
> nbformat                      5.7.0
> nest-asyncio                  1.6.0
> nose                          1.3.7
> numpy                         1.21.5
> open3d                        0.17.0
> opencv-contrib-python         4.9.0.80
> packaging                     24.0
> pandas                        1.1.5
> parso                         0.8.4
> pcl                           0.0.0.post1
> pexpect                       4.9.0
> pickleshare                   0.7.5
> Pillow                        9.4.0
> pip                           22.3.1
> pkgutil_resolve_name          1.3.10
> plotly                        5.18.0
> plyfile                       0.9
> prompt-toolkit                3.0.43
> ptyprocess                    0.7.0
> pycparser                     2.21
> pygicp                        0.0.1
> Pygments                      2.17.2
> pyOpenSSL                     23.0.0
> pyparsing                     3.1.2
> pyquaternion                  0.9.9
> pyrsistent                    0.19.3
> PySocks                       1.7.1
> python-dateutil               2.9.0.post0
> python-pcl                    0.3.0a1
> python_qt_binding             0.4.4
> pytz                          2024.1
> PyYAML                        6.0.1
> qt-dotgraph                   0.4.2
> qt-gui                        0.4.2
> qt-gui-cpp                    0.4.2
> qt-gui-py-common              0.4.2
> requests                      2.28.1
> resource_retriever            1.12.7
> retrying                      1.3.4
> rosbag                        1.14.13
> rosboost-cfg                  1.14.9
> rosclean                      1.14.9
> roscreate                     1.14.9
> rosgraph                      1.14.13
> roslaunch                     1.14.13
> roslib                        1.14.9
> roslint                       0.11.2
> roslz4                        1.14.13
> rosmake                       1.14.9
> rosmaster                     1.14.13
> rosmsg                        1.14.13
> rosnode                       1.14.13
> rosparam                      1.14.13
> rospy                         1.14.13
> rosservice                    1.14.13
> rostest                       1.14.13
> rostopic                      1.14.13
> rosunit                       1.14.9
> roswtf                        1.14.13
> rqt_action                    0.4.9
> rqt_bag                       0.5.1
> rqt_bag_plugins               0.5.1
> rqt_console                   0.4.9
> rqt_dep                       0.4.9
> rqt_graph                     0.4.11
> rqt_gui                       0.5.3
> rqt_gui_py                    0.5.3
> rqt-image-view                0.4.17
> rqt_launch                    0.4.8
> rqt_logger_level              0.4.8
> rqt-moveit                    0.5.10
> rqt_msg                       0.4.8
> rqt_nav_view                  0.5.7
> rqt_plot                      0.4.13
> rqt_pose_view                 0.5.8
> rqt_publisher                 0.4.8
> rqt_py_common                 0.5.3
> rqt_py_console                0.4.8
> rqt-reconfigure               0.5.4
> rqt_robot_dashboard           0.5.7
> rqt-robot-monitor             0.5.14
> rqt_robot_steering            0.5.10
> rqt_runtime_monitor           0.5.7
> rqt-rviz                      0.7.0
> rqt_service_caller            0.4.8
> rqt_shell                     0.4.9
> rqt_srv                       0.4.8
> rqt_tf_tree                   0.6.0
> rqt_top                       0.4.8
> rqt_topic                     0.4.11
> rqt_web                       0.4.8
> rviz                          1.13.30
> scikit-learn                  1.0.2
> scipy                         1.7.3
> sensor-msgs                   1.12.8
> setuptools                    65.6.3
> simple-knn                    0.0.0
> six                           1.16.0
> smach                         2.0.3
> smach_ros                     2.0.3
> smclib                        1.8.5
> tenacity                      8.2.3
> tf                            1.12.1
> tf_conversions                1.12.1
> tf2_geometry_msgs             0.6.5
> tf2_kdl                       0.6.5
> tf2_py                        0.6.5
> tf2_ros                       0.6.5
> threadpoolctl                 3.1.0
> topic_tools                   1.14.13
> torch                         1.12.1
> torchaudio                    0.12.1
> torchmetrics                  0.11.4
> torchvision                   0.13.1
> tqdm                          4.66.2
> traitlets                     5.9.0
> typing_extensions             4.4.0
> urdfdom-py                    0.4.6
> urllib3                       1.26.14
> wcwidth                       0.2.13
> Werkzeug                      2.2.3
> wheel                         0.38.4
> widgetsnbextension            4.0.10
> xacro                         1.13.20
> zipp                          3.15.0
> ```

The same issue I met with you.

**Comment by kk6398** [comment]
Do you have any methods to solve it??? Thank you

**Comment by KwanWaiPang** [comment]
I write a blog for the setup and testing of the GS-ICP-SLAM.
Hopefully, this can help to solve the problem.
And my suggestion is: use the conda to setup the environment following the guidance. And install the PCL using the follwoing command
`
pip install pcl
`
`
conda config --add channels conda-forge
`
`
conda install -c sirokujira python-pcl   
`
[CSDN blog](https://blog.csdn.net/gwplovekimi/article/details/137587778?spm=1001.2014.3001.5501)

**Comment by scut666** [comment]
I meet the same problem and I follow your solution install pcl and python-pcl. But this problem still remains. Do you have some advice to solve this?

pip list as follow:

action-msgs                          1.2.1
action-tutorials-interfaces          0.20.3
action-tutorials-py                  0.20.3
actionlib-msgs                       4.2.3
addict                               2.4.0
ament-cmake-test                     1.3.8
ament-copyright                      0.12.10
ament-cppcheck                       0.12.10
ament-cpplint                        0.12.10
ament-flake8                         0.12.10
ament-index-python                   1.4.0
ament-lint                           0.12.10
ament-lint-cmake                     0.12.10
ament-package                        0.14.0
ament-pep257                         0.12.10
ament-uncrustify                     0.12.10
ament-xmllint                        0.12.10
angles                               1.15.0
asttokens                            2.4.1
attrs                                23.2.0
blinker                              1.8.2
Brotli                               1.0.9
builtin-interfaces                   1.2.1
catkin-pkg                           1.0.0
certifi                              2024.2.2
charset-normalizer                   3.3.2
click                                8.1.7
colorama                             0.4.6
comm                                 0.2.2
composition-interfaces               1.2.1
ConfigArgParse                       1.7
contourpy                            1.2.1
cv-bridge                            3.2.1
cycler                               0.12.1
dash                                 2.17.0
dash-core-components                 2.0.0
dash-html-components                 2.0.0
dash-table                           5.0.0
decorator                            5.1.1
demo-nodes-py                        0.20.3
diagnostic-msgs                      4.2.3
diff_gaussian_rasterization          0.0.0
docutils                             0.21.2
domain-coordinator                   0.10.0
example-interfaces                   0.9.3
examples-rclpy-executors             0.15.1
examples-rclpy-minimal-action-client 0.15.1
examples-rclpy-minimal-action-server 0.15.1
examples-rclpy-minimal-client        0.15.1
examples-rclpy-minimal-publisher     0.15.1
examples-rclpy-minimal-service       0.15.1
examples-rclpy-minimal-subscriber    0.15.1
exceptiongroup                       1.2.1
executing                            2.0.1
fastjsonschema                       2.19.1
Flask                                3.0.3
fonttools                            4.51.0
geometry-msgs                        4.2.3
idna                                 3.7
image-geometry                       3.2.1
importlib_metadata                   7.1.0
interactive-markers                  2.3.2
ipython                              8.24.0
ipywidgets                           8.1.2
itsdangerous                         2.2.0
jedi                                 0.19.1
Jinja2                               3.1.4
joblib                               1.4.2
jsonschema                           4.22.0
jsonschema-specifications            2023.12.1
jupyter_core                         5.7.2
jupyterlab_widgets                   3.0.10
kiwisolver                           1.4.5
laser-geometry                       2.4.0
launch                               1.0.5
launch-ros                           0.19.7
launch-testing                       1.0.5
launch-testing-ros                   0.19.7
launch-xml                           1.0.5
launch-yaml                          1.0.5
lifecycle-msgs                       1.2.1
lightning-utilities                  0.11.2
logging-demo                         0.20.3
map-msgs                             2.1.0
MarkupSafe                           2.1.5
matplotlib                           3.8.4
matplotlib-inline                    0.1.7
message-filters                      4.3.3
mkl-fft                              1.3.1
mkl-random                           1.2.2
mkl-service                          2.4.0
nav-msgs                             4.2.3
nbformat                             5.10.4
nest-asyncio                         1.6.0
numpy                                1.24.3
open3d                               0.18.0
opencv-contrib-python                4.9.0.80
osrf-pycommon                        2.0.2
packaging                            24.0
pandas                               2.2.2
parso                                0.8.4
pcl                                  0.0.0.post1
pcl-msgs                             1.0.0
pendulum-msgs                        0.20.3
pexpect                              4.9.0
Pillow                               9.4.0
pip                                  24.0
platformdirs                         4.2.1
plotly                               5.22.0
plyfile                              1.0.3
pretty-errors                        1.2.25
prompt-toolkit                       3.0.43
ptyprocess                           0.7.0
pure-eval                            0.2.2
pyarrow                              16.0.0
pygicp                               0.0.1
Pygments                             2.18.0
pyparsing                            3.1.2
pyquaternion                         0.9.9
PySocks                              1.7.1
python-dateutil                      2.9.0.post0
python-qt-binding                    1.1.2
pytz                                 2024.1
PyYAML                               6.0.1
qt-dotgraph                          2.2.3
qt-gui                               2.2.3
qt-gui-cpp                           2.2.3
qt-gui-py-common                     2.2.3
quality-of-service-demo-py           0.20.3
rcl-interfaces                       1.2.1
rclpy                                3.3.12
rcutils                              5.1.5
referencing                          0.35.1
requests                             2.31.0
rerun-sdk                            0.15.1
resource-retriever                   3.1.1
retrying                             1.3.4
rmw-dds-common                       1.6.0
ros2action                           0.18.9
ros2bag                              0.15.9
ros2cli                              0.18.9
ros2component                        0.18.9
ros2doctor                           0.18.9
ros2interface                        0.18.9
ros2launch                           0.19.7
ros2lifecycle                        0.18.9
ros2multicast                        0.18.9
ros2node                             0.18.9
ros2param                            0.18.9
ros2pkg                              0.18.9
ros2run                              0.18.9
ros2service                          0.18.9
ros2topic                            0.18.9
rosbag2-interfaces                   0.15.9
rosbag2-py                           0.15.9
rosgraph-msgs                        1.2.1
rosidl-adapter                       3.1.5
rosidl-cli                           3.1.5
rosidl-cmake                         3.1.5
rosidl-generator-c                   3.1.5
rosidl-generator-cpp                 3.1.5
rosidl-generator-py                  0.14.4
rosidl-parser                        3.1.5
rosidl-runtime-py                    0.9.3
rosidl-typesupport-c                 2.0.1
rosidl-typesupport-cpp               2.0.1
rosidl-typesupport-fastrtps-c        2.2.2
rosidl-typesupport-fastrtps-cpp      2.2.2
rosidl-typesupport-introspection-c   3.1.5
rosidl-typesupport-introspection-cpp 3.1.5
rpds-py                              0.18.1
rpyutils                             0.2.1
rqt-action                           2.0.1
rqt-bag                              1.1.4
rqt-bag-plugins                      1.1.4
rqt-console                          2.0.3
rqt-graph                            1.3.0
rqt-gui                              1.1.7
rqt-gui-py                           1.1.7
rqt-msg                              1.2.0
rqt-plot                             1.1.2
rqt-publisher                        1.5.0
rqt-py-common                        1.1.7
rqt-py-console                       1.0.2
rqt-reconfigure                      1.1.2
rqt-service-caller                   1.0.5
rqt-shell                            1.0.2
rqt-srv                              1.0.3
rqt-topic                            1.5.0
scikit-learn                         1.4.2
scipy                                1.13.0
sensor-msgs                          4.2.3
sensor-msgs-py                       4.2.3
setuptools                           69.5.1
shape-msgs                           4.2.3
simple_knn                           0.0.0
six                                  1.16.0
sros2                                0.10.4
stack-data                           0.6.3
statistics-msgs                      1.2.1
std-msgs                             4.2.3
std-srvs                             4.2.3
stereo-msgs                          4.2.3
teleop-twist-keyboard                2.4.0
tenacity                             8.3.0
tf2-geometry-msgs                    0.25.6
tf2-kdl                              0.25.6
tf2-msgs                             0.25.6
tf2-py                               0.25.6
tf2-ros-py                           0.25.6
tf2-tools                            0.25.6
threadpoolctl                        3.5.0
topic-monitor                        0.20.3
torch                                1.12.1
torchaudio                           0.12.1
torchmetrics                         1.4.0
torchvision                          0.13.1
tqdm                                 4.66.4
traitlets                            5.14.3
trajectory-msgs                      4.2.3
turtlesim                            1.4.2
typing_extensions                    4.11.0
tzdata                               2024.1
unique-identifier-msgs               2.2.1
urllib3                              2.2.1
visualization-msgs                   4.2.3
wcwidth                              0.2.13
Werkzeug                             3.0.3
wheel                                0.43.0
widgetsnbextension                   4.0.10
zipp                                 3.18.1

**Comment by huarzail** [comment]
I had encountered this same error. You can attempt to change the fast-gicp branch of gs_fast_slm.

**Comment by scpoppin1207** [comment]
I've tried this method but error still occurs.
Then I changed the fast-gicp branch of gs_fast_slm but it doesn't work, neither.
HOW TO SOLVE THIS ISSUE?

> I write a blog for the setup and testing of the GS-ICP-SLAM. Hopefully, this can help to solve the problem. And my suggestion is: use the conda to setup the environment following the guidance. And install the PCL using the follwoing command `pip install pcl` `conda config --add channels conda-forge` `conda install -c sirokujira python-pcl ` [CSDN blog](https://blog.csdn.net/gwplovekimi/article/details/137587778?spm=1001.2014.3001.5501)

**Comment by Zlzxzw1234** [comment]
This problem has be solved by install the PCL：
pip install pcl 
conda config --add channels conda-forge
conda install -c sirokujira python-pcl

but when I run the conda install -c sirokujira python-pcl, it has a problem

Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.

ResolvePackageNotFound: 
  - python==3.9



方便问一下，python具体是python3.9.几吗？不知道为什么，我的python是3.9.21，但是安装python-pcl的时候，一直显示找不到python3.9
